#! /usr/bin/env bash

#########################################################
## Keys
#########################################################

_keysToLoadHelp () {
echo '

Error:  Missing KEYME_KEYS_TO_LOAD Environment

Syntax:
  $bitwarden_id<space>$friendly_name_on_your_disk

Example:

export KEYME_KEYS_TO_LOAD="
abcc0def-b123-8803-b11d-bc9999f99po0 example1
abcc0def-b123-8803-b11d-bc9999f99po1 example2
abcc0def-b123-8803-b11d-bc9999f99po2 id_rsa
"
'

}

# _lastPassUserHelp () {
# echo '

# Error:  Missing LASTPASS_USER Environment

# Syntax:
#   export LASTPASS_USER="jdoe@email.com"

# You should probably set this in your bashrc or zshrc
# '
# }

_purgeIfEmpty () {
  CHECK=$(cat $1)
  if [ -z "${CHECK}" ]; then
    echo Removing Empty: $1
    rm "$1"
  fi
}

_chmod () {
  [ -f "$2" ] && chmod $1 "$2"
}

TMP_SSH_KEY_DIR="/tmp/.ssh"
add_key () {
  echo Installing Key: $2
  # lpass show "$1" --field "Private Key" > "${TMP_SSH_KEY_DIR}/$2"
  # lpass show "$1" --field "Public Key" > "${TMP_SSH_KEY_DIR}/$2.pub"
  bwGetItem "$1" | jq -r '.notes' > "${TMP_SSH_KEY_DIR}/$2"
  # bwGetItem "$1" | jq -r '.fields[1] .value' > "${TMP_SSH_KEY_DIR}/$1.pub"
  #TODO: igure this out - not complete
  # bwGetItem "$1" | jq -r '.fields[] | select(.name=="public") | .value' > "${TMP_SSH_KEY_DIR}/$2.pub" 2> /dev/null
  _purgeIfEmpty "${TMP_SSH_KEY_DIR}/$2"
  # _purgeIfEmpty "${TMP_SSH_KEY_DIR}/$1.pub"
  _chmod 400 "${TMP_SSH_KEY_DIR}/$2"
  # _chmod 400 "${TMP_SSH_KEY_DIR}/$1.pub"
}

keyme () {
  [ -z "${KEYME_KEYS_TO_LOAD}" ] && _keysToLoadHelp && return
  # [ -z "${LASTPASS_USER}" ] && _lastPassUserHelp && return
  # echo Lastpass login...
  # 2>&1 lpass ls > /dev/null || lpass login "${LASTPASS_USER}"
  echo Purging "${TMP_SSH_KEY_DIR}"
  [ -d "${TMP_SSH_KEY_DIR}" ] && rm -rf "${TMP_SSH_KEY_DIR}"
  echo Making tmp dir "${TMP_SSH_KEY_DIR}"...
  mkdir -p "${TMP_SSH_KEY_DIR}" 2> /dev/null
  # chown $USER:$USER "${TMP_SSH_KEY_DIR}" # doesn't work on mac
  chmod 700 "${TMP_SSH_KEY_DIR}"
  echo Purging "${HOME}/.ssh"
  [ -d $HOME/.ssh ] && rm -rf $HOME/.ssh
  ln -s "${TMP_SSH_KEY_DIR}" "${HOME}/.ssh"
  IFS=$'\n'
  for key_and_name in $(echo "${KEYME_KEYS_TO_LOAD}"); do
    local id=$(echo $key_and_name | awk '{print $1}')
    local name=$(echo $key_and_name | awk '{print $2}')
    add_key "${id}" "${name}"
  done
}

agentme () {
  sudo killall ssh-agent
  eval `ssh-agent`
  ssh-add "${HOME}/.ssh/"* \
    1> /dev/null \
    2> /dev/null
}
