#! /usr/bin/env bash

export DIR_TERRAFORM="${HOME}/.terraform"

# list of terraform versions I like to use
TERRAFORM_VERSIONS_TO_DOWNLOAD="${TERRAFORM_VERSIONS_TO_DOWNLOAD:-1.5.7 0.12.31}"
DEFAULT_TERRAFORM_VERSION="1.5.7"

# create TF directory
mkdir -p "${DIR_TERRAFORM}";

# download terraform (mac/darwin) versions I like to keep locally
#TODO: smarten this up to detect OS for when I switch to linux
for terraform_version in $(echo $TERRAFORM_VERSIONS_TO_DOWNLOAD); do
  TF_VERSION_ZIP="${DIR_TERRAFORM}/terraform_${terraform_version}_darwin_amd64.zip"
  if [ ! -f "${TF_VERSION_ZIP}" ]; then
    curl -o "${TF_VERSION_ZIP}" "https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_darwin_amd64.zip"
  fi
done

# first time install only, I want to unzip terraform so its ready to go
if [ ! -f "${DIR_TERRAFORM}/terraform" ]; then
  unzip "${DIR_TERRAFORM}/terraform_${DEFAULT_TERRAFORM_VERSION}_darwin_amd64.zip" -d "${DIR_TERRAFORM}"
fi

# Setup Terraform in PATH
# ---------
if [[ ! "$PATH" == *"${DIR_TERRAFORM}"* ]]; then
  export PATH="${PATH:+${PATH}:}"${DIR_TERRAFORM}""
fi
